### ISSUE TITLE
Dataset Access

### ISSUE THREAD

**Issue by melihyazgan** [AIR-THU/DAIR-RCooper#1]
Hi,

it is not possible to download the dataset or even register myself in Platform to download the dataset in English page.
Is it forbidden to use the dataset outside mainland china or researchers like me are allowed to download it?

Greetings,
Melih

**Comment by leofansq** [comment]
Sorry for the inconvenience. The dataset will be public availuable for all researchers, and we are working on that.

**Comment by githigher** [comment]
I have left my email address on https://www.t3caic.com/qingzhen/. It's been two days since I requested to download the data, when will I get a reply?

**Comment by ryhnhao** [comment]
Thanks for your attention to our work.
We are sorry for the late reply. 

We will contact the [CAIC Corporation](https://www.t3caic.com/qingzhen/) to find a more efficient strategy. 
For now, they manually reply to the data request.

**Comment by leofansq** [comment]
> I have left my email address on https://www.t3caic.com/qingzhen/. It's been two days since I requested to download the data, when will I get a reply?

All the requests last week are already responsed via email, sorry for the late reply.

**Comment by melihyazgan** [comment]
> Sorry for the inconvenience. The dataset will be public availuable for all researchers, and we are working on that.

Do you have time schedule for that?

**Comment by leofansq** [comment]
> > Sorry for the inconvenience. The dataset will be public availuable for all researchers, and we are working on that.
> 
> Do you have time schedule for that?

According to the response from CAIC, they have already responsed and released the dataset to all the researchers via email, including the researchers from the institute outside mainland China, e.g.,  TUM, KIT, and CMU.

**Comment by melihyazgan** [comment]
> > > Sorry for the inconvenience. The dataset will be public availuable for all researchers, and we are working on that.
> > 
> > 
> > Do you have time schedule for that?
> 
> According to the response from CAIC, they have already responsed and released the dataset to all the researchers via email, including the researchers from the institute outside mainland China, e.g., TUM, KIT, and CMU.

ah, okay, then I have to register myself on the Chinese page. Thank you

**Comment by leofansq** [comment]
> > > > Sorry for the inconvenience. The dataset will be public availuable for all researchers, and we are working on that.
> > > 
> > > 
> > > Do you have time schedule for that?
> > 
> > 
> > According to the response from CAIC, they have already responsed and released the dataset to all the researchers via email, including the researchers from the institute outside mainland China, e.g., TUM, KIT, and CMU.
> 
> ah, okay, then I have to register myself on the Chinese page. Thank you

The English version is on the way.  For now, the instruction figure in README may be helpful. Sorry for the inconvenience again.
