### ISSUE TITLE
 How much GPU memory is required to run the code.

### ISSUE THREAD

**Issue by CBY-9527** [AIR-THU/DAIR-RCooper#10]
Thank you very much for sharing the code. When I attempted to train the cobevt model on my 24GB 3090 GPU (using the command: python opencood_plugin/opencood/tools/train.py --hypes_yaml configs/intersection_cobevt.yaml), even with a batch size set to 1, I still encountered out-of-memory errors

**Comment by leofansq** [comment]
Yes, the training cost for CoBEVT is a little bit high. It requeires around 25.5G GPU memory when the batch size is set to 1.
