### ISSUE TITLE
Dataset Access

### ISSUE THREAD

**Issue by melihyazgan** [AIR-THU/DAIR-RCooper#14]
Hi again,

I requested data access by filling the Chinese Form. Because I don't have a china phone number, I created a random one by requesting.  On the other hand, I wrote an email to bd@t3caic.com to get access to the dataset. Till now  I haven't received any feedback.
Both of them were requested by using the official email address yazgan@fzi.de.

Could you please support me?

Kind Regards,
Melih Yazgan

**Comment by leofansq** [comment]
> Hi again,
> 
> I requested data access by filling the Chinese Form. Because I don't have a china phone number, I created a random one by requesting. On the other hand, I wrote an email to [bd@t3caic.com](mailto:bd@t3caic.com) to get access to the dataset. Till now I haven't received any feedback. Both of them were requested by using the official email address [yazgan@fzi.de](mailto:yazgan@fzi.de).
> 
> Could you please support me?
> 
> Kind Regards, Melih Yazgan

Sorry again, we will contact the CAIC group.

**Comment by leofansq** [comment]
Hi,

The CAIC group has sent the email to your address. Sorry for the inconvenience.

Best Regards,
Siqi
