### ISSUE TITLE
117-118-120-119场景相机内外参准确性问题

### ISSUE THREAD

**Issue by XuelianZ** [AIR-THU/DAIR-RCooper#15]
你好，感谢开源数据集。我基于开源数据集，将路口场景的标注框投影到多视角图像上，发现117-118-120-119在图像上的投影非常不准确（或仅有120相机较准确），但是同样的脚本在136-137-138-139路口画出的投影，四个视角都较准确。117、118、119三个相机的外参是否存在较大偏差？

这是 117-118-120-119 路口的投影图。左上角红字是 序号_cam-ip。可以看到左下角的120视图相对较准确，其他偏差很大。
![2d0390d445d32e5197a71f1c3b3ba6b](https://github.com/AIR-THU/DAIR-RCooper/assets/40563085/c8adf93a-37a6-42e9-9d1f-7d4b438951f4)

这是 136-137-138-139 路口的投影图。可以看到投影相对准确。
![8191b12a23141ca6f94af5b69b2b6c8](https://github.com/AIR-THU/DAIR-RCooper/assets/40563085/7538ac2f-6e94-4619-91b4-400736afac9e)

**Comment by ryhnhao** [comment]
你好，感谢你指出这个问题。
这个问题在我们的验证中也确实存在，路口场景117-120的标定并不准确。这影响了camera-based方法在RCooper路口场景下的实践。
我们会与CAIC协作来继续更新相机内外参。
