### ISSUE TITLE
Dataset access

### ISSUE THREAD

**Issue by Uchan1996** [AIR-THU/DAIR-RCooper#19]
Hi, thank you for your great work!
I requested the dataset via [https://www.t3caic.com/qingzhen/](url) last Friday, but I haven't received any response.
I entered a random phone number since I don't have Chinese one like [https://github.com/AIR-THU/DAIR-RCooper/issues/14#issue-2285035161](url)
Do you know how many days it takes to get a response?
I would appreciate it if you could tell me that.

**Comment by carrolltm** [comment]
I have also filled in the relevant information on the corresponding website, but I have not received any reply so far

**Comment by Uchan1996** [comment]
I have got the access to the datasets today.
Thank you.

**Comment by M0NSTERCOCO** [comment]
Hi! I have filled out the information last Friday, do I have to wait a week to receive a response?

**Comment by geekabel** [comment]
Hi, thank you for your great work! I requested the dataset but even if I put random chinese number, I can submit the form. Is it normal . How do you do it  @Uchan1996

**Comment by Uchan1996** [comment]
@geekabel 
I also put random numbers for Chinese phone number and received the dataset access.
I followed this issue [https://github.com/AIR-THU/DAIR-RCooper/issues/14](url).

**Comment by ryhnhao** [comment]
Hi,
Thanks for your attention to our work.

You can request the dataset as the instruction in [Readme](https://github.com/AIR-THU/DAIR-RCooper).
The [CAIC](https://www.t3caic.com/qingzhen/) manually respond to the dataset request once a week (which may also be affected by the Chinese traditional festival :).

If you haven't received a response 8 or 9 days after submitting your application, you can drop your information in [this issue](https://github.com/AIR-THU/DAIR-RCooper/issues/22). We will help to contact CAIC.
