### ISSUE TITLE
Camera APIs

### ISSUE THREAD

**Issue by githigher** [AIR-THU/DAIR-RCooper#2]
Thank you very much for your contribution to the new dataset!
Although the RCooper dataset contains both Lidar and RGB data, do you only provide an API for Lidar data, and do the baseline tests in your paper not use RGB data?
Looking forward to your reply.

**Comment by ryhnhao** [comment]
Thank you for your attention to our work!

Given limited time, we only release the whole LiDAR-based benchmark results.
We are still trying to construct the camera-based benchmark, which may appear in our future work.

Indeed, you can perform camera-based perception based on our dataset. 

Notes: the data annotation of our datasets is based on point cloud data, and meanwhile the sensing range of camera group is smaller than that of LiDAR group, which means that the label may need filtering on demand considering camera group's view.
