### ISSUE TITLE
数据集权限

### ISSUE THREAD

**Issue by guoge010322** [AIR-THU/DAIR-RCooper#20]
感谢作者优秀的工作，希望能申请通过数据集权限！

**Comment by ryhnhao** [comment]
您好，感谢您对我们工作的关注。您可以根据[Readme](https://github.com/AIR-THU/DAIR-RCooper)中的说明请求数据集。
更多的数据集申请相关信息可以参考这个[issue](https://github.com/AIR-THU/DAIR-RCooper/issues/22)
