### ISSUE TITLE
How to reproduce Fig 6 results?

### ISSUE THREAD

**Issue by sethzhao506** [AIR-THU/DAIR-RCooper#21]
Dear authors,

Thanks for your nice work! I'm wondering if there's instruction on reproducing the Fig 6 results without MEMS sensor? Specifically, how do you remove MEMS sensors from both training & validation sets? Thank you.

**Comment by leofansq** [comment]
You can get the LiDAR's type according to the infrastructure's IDs and leverage the Multiline sensors for experiments. 
Multiline LiDAR: 117, 120, 136, 139
MEMS LiDAR: 118, 119, 137, 138

* For the raw RCooper dataset, you can directly distinguish the ID in data folder.
* For the converted OPV2V-format or V2V4Real-format dataset, you can distinguish the infrastructures according to the following mapping relationship
    * '116-115' scenario: 116 ---> 0, 115 ---> 1
    * '106-105' scenario: 106 ---> 0, 105 ---> 1
    * '117-118-120-119' scenario: 117 ---> 0, 118 ---> 1, 120 ---> 2, 119 ---> 3
    * '136-137-138-139' scenario: 136 ---> 0, 137 ---> 1, 138 ---> 2, 139 ---> 3

**Comment by sethzhao506** [comment]
Thanks for your response! However, if I only use all multiline sensors for training & testing, it doesn't show much performance increase. Could you specify how you train with multiline sensors in the intersection scenarios?

**Comment by leofansq** [comment]
We only convert the multiline sensors' data to V2V4Real format and use the same training script for this data-level ablation study.

**Comment by sethzhao506** [comment]
Thank you for your help!
