### ISSUE TITLE
数据

### ISSUE THREAD

**Issue by guoge010322** [AIR-THU/DAIR-RCooper#23]
![pcd](https://github.com/AIR-THU/DAIR-RCooper/assets/154695130/38919138-95d8-4a2b-b3ef-4e61ae0bde89)

非常感谢您的贡献！作为新手想请教一个问题：论文中指出
激光雷达正下方区域存在盲点，但我观察数据发现并没有这种情况，请问是我的理解有问题吗？希望得到您的回复

**Comment by guoge010322** [comment]
还有一个问题想请教，您认为在路端协同方面，比如针对您这个数据集，引入多序列时序信息是否会有一定帮助

**Comment by ryhnhao** [comment]
Hello, guoge
图中所示其实是已经 融合 80线LiDAR 和 32线LiDAR 后的点云，通过这种LiDAR group组合，已经解决了正下方点云盲点的问题。图示的方案其实正说明我们的LiDAR group组合能够有效感知下方区域。


> ![pcd](https://private-user-images.githubusercontent.com/154695130/340070055-38919138-95d8-4a2b-b3ef-4e61ae0bde89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2ODg1NjQsIm5iZiI6MTcxODY4ODI2NCwicGF0aCI6Ii8xNTQ2OTUxMzAvMzQwMDcwMDU1LTM4OTE5MTM4LTk1ZDgtNGEyYi1iM2VmLTRlNjFhZTBiZGU4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQwNTI0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjM2YzI3NGMzOGJiMGFjMzI3ZTFmNmYwNWI4NzM2NTdjNzA2OTRhNDZkODYxMTQ0Y2JmYTAzNDE1YTI1MDk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jnw9NN-6wCItZ_gNDUB8N9zFUUIePpkjBXBGWW5lu50)
> 
> 非常感谢您的贡献！作为新手想请教一个问题：论文中指出 激光雷达正下方区域存在盲点，但我观察数据发现并没有这种情况，请问是我的理解有问题吗？希望得到您的回复

**Comment by ryhnhao** [comment]
> 还有一个问题想请教，您认为在路端协同方面，比如针对您这个数据集，引入多序列时序信息是否会有一定帮助

这确实是一个值得探索开放性问题，时序信息对于自动驾驶感知往往具有重要的意义，尤其是tracking、prediction、planning任务中，时序信息的引入可能会有效提升效果。对detection而言，时序信息的引入往往对于动态目标对象检测或者提升检测器效率具有意义

**Comment by guoge010322** [comment]
非常感谢您的回复！还有个问题想请教，路段协同和车路协同相比，也是有一个ego的对吗？相对于车路协同这种协助ego车进行驾驶的作用，路端协同的意义体现在什么方面，是对所需的ego路端基础设施点进行一个协助吗？（非常感谢您的回复，可能新手问题比较不成熟，望见谅~）

**Comment by ryhnhao** [comment]
谢谢你的提问，你的问题很敏锐

路段感知（roadside perception）本来就是一个值得的研究方向，正如我们在相关工作2.1节所列举的，其不仅能够对自动驾驶提供更多的环境感知信息，也能够为智能交通管理等场景服务。但是roadside perception面临盲点和感知范围有限的问题，所以**路段感知需要协作**

在广泛意义的路段感知场景下并没有ego car这个中心主体，正如我们对RCooper任务的定义，其目标是对于一个“区域”内三维目标的感知。
但是目前的协作感知框架均是以ego-car为中心主体的协作感知。因此在应用这些框架时不可避免得需要指定一个基础设施点为ego （我们在选择这个ego时是随机的） :)

事实上，抛开现有框架来研究一个新的无ego基准方法也是值得做的开放性问题。我们鼓励社区来探索！
谢谢

**Comment by guoge010322** [comment]
非常感谢您的回复！
