### ISSUE TITLE
how to get the save_vis or show_vis

### ISSUE THREAD

**Issue by YuJiXYZ** [AIR-THU/DAIR-RCooper#26]
hello, thanks for your outstanding work. 
When I try to use the save_vis or show_vis command during the inference period, I meet the problem as the picture, can you help me? Thank you!
![image](https://github.com/AIR-THU/DAIR-RCooper/assets/106587670/e3a3e829-9244-4984-99e1-46a491d2722f)

**Comment by ryhnhao** [comment]
Hi @YuJiXYZ 
Thanks for your attention to our work!
Indeed, we didn't try the show_vis or save_vis command in the opencood environment. Our visualization is via SUSTech tools.
It seems to be caused by the wrong use of open3d. 

Maybe the figure below may help you debug
i.e. replace   _**origin_lidar[:, :3]**_   to   _**origin_lidar[:, :3].values**_


![image](https://github.com/AIR-THU/DAIR-RCooper/assets/153728596/5b54cdee-f023-4e9e-b8dd-5dfe570109b1)

**Comment by DeepPhysicVision** [comment]
> Hi @YuJiXYZ Thanks for your attention to our work! Indeed, we didn't try the show_vis or save_vis command in the opencood environment. Our visualization is via SUSTech tools. It seems to be caused by the wrong use of open3d.
> 
> Maybe the figure below may help you debug i.e. replace _**origin_lidar[:, :3]**_ to _**origin_lidar[:, :3].values**_
> 
> ![image](https://private-user-images.githubusercontent.com/153728596/341956892-5b54cdee-f023-4e9e-b8dd-5dfe570109b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTExOTEsIm5iZiI6MTcxOTQ5MDg5MSwicGF0aCI6Ii8xNTM3Mjg1OTYvMzQxOTU2ODkyLTViNTRjZGVlLWYwMjMtNGU5ZS1iOGRkLTVkZmU1NzAxMDliMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QxMjIxMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00N2I2MmI3MWMzNmJhMzMzNDY2NDMwMjcxYzgyY2QwYWY3NTFmYjdhMTkwYzU1MDc0YmVhNDExZmUyMjNjY2U5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-_ZoYVD5vr0T_hgyuNT6bwmUxoBMWqPNLeHTiyZrgQM)

I have try before with this way "i.e. replace origin_lidar[:, :3] to origin_lidar[:, :3].values" and it can't slow the problem. Could you write a simple doc via SUSTech tools for this project, may be it will help us a lot, thanks!
