### ISSUE TITLE
遮挡情况与数据集意义

### ISSUE THREAD

**Issue by guoge010322** [AIR-THU/DAIR-RCooper#27]
您好！我观察发现由于路端的上帝视角，您的数据集中的车辆几乎不存在遮挡情况，或者说没有遮挡情况。想请教一下，如果只考虑激光雷达的话，在路端协同数据集中，检测不出来的车具体是哪些情况？或者它需要解决哪些问题？需要从哪方面优化提升效果？期待您的回复！

**Comment by ryhnhao** [comment]
您好，您可以参考补充材料中对路口的场景可视化，存在公交车、大货车这种大型车辆，其会造成部分视角的遮挡。
同一个目标在A视角的视觉盲区，但在B视角的补充下可以看到，那么协同感知就能解决A视角感知不到的问题。
您可以再次参考引言和结论的limitation部分，来思考改进方向。我们认为这是一个开放性问题！谢谢

**Comment by ryhnhao** [comment]
当然，我们也承认本数据集的局限性。如果在更复杂的路段上采集数据，这个意义的说明应该会更显著一些 :)
期待有更多的工作来丰富数据、探索方法

**Comment by guoge010322** [comment]
是的，因为我观察到"occluded_state"的值都是0，是不是也就意味着没有车辆存在遮挡情况

**Comment by guoge010322** [comment]
> 当然，我们也承认这个数据库的复杂性。如果在更复杂的道路上收集数据，这个意义的说明应该会更显著一些:) 期待有工作来丰富数据、探索方法。

因为观察到“occluded_state”的值都是0，是不是意味着没有车辆存在遮挡情况

**Comment by ryhnhao** [comment]
> > 当然，我们也承认这个数据库的复杂性。如果在更复杂的道路上收集数据，这个意义的说明应该会更显著一些:) 期待有工作来丰富数据、探索方法。
> 
> 因为观察到“occluded_state”的值都是0，是不是意味着没有车辆存在遮挡情况

在部分场景下，遮挡是明显的。

occcluded_state=0也包含了部分遮挡。另外，实质上，原始label其实只包含了该点云下能看到的情况（标注员才会去标），看不到的目标就不会标注出来，所以所谓occcluded_state参数全都是0。预处理中也需要去融合label。

**Comment by guoge010322** [comment]
> > > 当然，我们也承认这个数据库的复杂性。如果在更复杂的道路上收集数据，这个意义的说明应该会更显著一些:) 期待有工作来丰富数据、探索方法。
> > 
> > 
> > 因为观察到“occluded_state”的值都是0，是不是意味着没有车辆存在遮挡情况
> 
> 在部分场景下，遮挡是明显的。
> 
> occcluded_state=0也包含了部分遮挡。另外，实质上，原始label其实只包含了该点云下能看到的情况（标注员才会去标），看不到的目标就不会标注出来，所以所谓occcluded_state参数全都是0。预处理中也需要去融合label。

原来如此，所以说occluded_state=0并不代表这个车没有遮挡，可以这么理解吗？是标注数据时候没有考虑这个参数吗~

**Comment by ryhnhao** [comment]
> > > > 当然，我们也承认这个数据库的复杂性。如果在更复杂的道路上收集数据，这个意义的说明应该会更显著一些:) 期待有工作来丰富数据、探索方法。
> > > 
> > > 
> > > 因为观察到“occluded_state”的值都是0，是不是意味着没有车辆存在遮挡情况
> > 
> > 
> > 在部分场景下，遮挡是明显的。
> > occcluded_state=0也包含了部分遮挡。另外，实质上，原始label其实只包含了该点云下能看到的情况（标注员才会去标），看不到的目标就不会标注出来，所以所谓occcluded_state参数全都是0。预处理中也需要去融合label。
> 
> 原来如此，所以说occluded_state=0并不代表这个车没有遮挡，可以这么理解吗？是标注数据时候没有考虑这个参数吗~

是的～

**Comment by guoge010322** [comment]
> > > > > 当然，我们也承认这个数据库的复杂性。如果在更复杂的道路上收集数据，这个意义的说明应该会更显著一些:) 期待有工作来丰富数据、探索方法。
> > > > 
> > > > 
> > > > 因为观察到“occluded_state”的值都是0，是不是意味着没有车辆存在遮挡情况
> > > 
> > > 
> > > 在部分场景下，遮挡是明显的。
> > > occcluded_state=0也包含了部分遮挡。另外，实质上，原始label其实只包含了该点云下能看到的情况（标注员才会去标），看不到的目标就不会标注出来，所以所谓occcluded_state参数全都是0。预处理中也需要去融合label。
> > 
> > 
> > 原来如此，所以说occluded_state=0并不代表这个车没有遮挡，可以这么理解吗？是标注数据时候没有考虑这个参数吗~
> 
> 是的～

感谢您的耐心回复！~我是否可以理解为rcooper数据集在仅激光雷达下存在这样的情况：有一辆车，经过了A传感器，一段时间后经过了B传感器但是在B视角下可能由于货车被部分遮挡。
