### ISSUE TITLE
weird image masks

### ISSUE THREAD

**Issue by bbzh** [AIR-THU/DAIR-RCooper#28]
Hi, 

Thanks for releasing the dataset. The images are often with weird masks; an example is shown below. Are these artifacts?

<img width="1546" alt="Screenshot 2024-06-23 at 9 28 03 PM" src="https://github.com/AIR-THU/DAIR-RCooper/assets/29305317/dfc28b24-50c4-4d89-a968-c0b8d045d9ba">

**Comment by leofansq** [comment]
Yes, they are artifacts. Due to the large amount of data, we adopted the automatical masking approach for privacy protection (e.g., licence plate). It seems that there are omissions during the manual double-check. Could you share the image id?

**Comment by bbzh** [comment]
The example after converting to VVReal is in RCooper2VVReal/intersection/train/136-137-138-139_seq-008/1. In fact, they are not uncommon across the entire datasets.
