### ISSUE TITLE
There is not an "intersection_no" folder in "codes/ckpts".

### ISSUE THREAD

**Issue by Uchan1996** [AIR-THU/DAIR-RCooper#29]
Thank you for your great work.
I cannot find an `intersection_no` folder in `codes/ckpts`.
Could you please check that?

**Comment by ryhnhao** [comment]
Hi @Uchan1996 
The ckpts of no_fusion and late_fusion are the same. The later only combines the det results of no_fusion method.
You can refer to [det_inference_intersection_nofusion.sh](https://github.com/AIR-THU/DAIR-RCooper/blob/main/codes/scripts/det_inference_intersection_nofusion.sh) to run the inference.

**Comment by Uchan1996** [comment]
@ryhnhao 
Thank you for your reply.
The `config.yaml`of no fusion in intersection is also the same as late fusion?

**Comment by ryhnhao** [comment]
> @ryhnhao Thank you for your reply. The `config.yaml`of no fusion in intersection is also the same as late fusion?

Hi @Uchan1996 
Yes, they are totally the same.
The **--fusion_method** in sh scripts indicates whether it's no or late.

**Comment by Uchan1996** [comment]
Thank you very much!
