### ISSUE TITLE
内存大

### ISSUE THREAD

**Issue by guoge010322** [AIR-THU/DAIR-RCooper#31]
我训练发现where2comm，cobevt模型跑起来都需要很大内存，请问是因为数据本身导致的吗

**Comment by ryhnhao** [comment]
您好，路端协同感知的感知范围更大，因此在config中的range设置得很大，这会导致资源消耗的增大

在这些issue中你也许可以看到更多资源消耗的讨论：https://github.com/AIR-THU/DAIR-RCooper/issues/10 ；https://github.com/AIR-THU/DAIR-RCooper/issues/16
