### ISSUE TITLE
BBox Shift during Visualization because of Inaccurate Calibration

### ISSUE THREAD

**Issue by Uchan1996** [AIR-THU/DAIR-RCooper#32]
Hi, I have a question about visualization of ground truth bounding boxes.
The codes provide only visulalization of GT boxes on a bird's eye view as far as I've found, but I want to visualize them on each camera view.
In my understanding, the `gt_box_tensor` on the line 115 in `inference.py` is on the ego lidar coordinate.
So I transformed `gt_box_tensor` by multiplying the inverse of `transformation_matrix`, each extrinsic and each intrinsic to obtain bboxes on each image coordinate.
The `transformation matrix` is a matrix to project each lidar coordinate to `ego` coordinate, which is calculated in the line 444 of 'basedataset.py'.
However, the projected bboxes seem inaccurate, and there are sometimes weird bboxes, e.g., bboxes in mid-air.
The transformation I did is wrong? Or extrinsics are inaccurate?
Also, could you please publish your code to visualize bboxes on each camera view if you have.

The examples of visualization results are like below. The green boxes represent the projected GT boxes.

![view1_camera0_150](https://github.com/user-attachments/assets/568595ef-7caf-4556-b7f8-82ccdcb3ef90)

![view1_camera0_37](https://github.com/user-attachments/assets/98815325-1937-4a8d-927c-5666633a1de2)

![view1_camera0_119](https://github.com/user-attachments/assets/d8af912c-02ca-4ea7-9131-cb00ad59ecf8)

**Comment by ryhnhao** [comment]
Sorry for the late response. Thank you for pointing this out. This problem does exist in our verification.
The calibration of the intersection scene 117-120 is not accurate. This affects the practice of camera-based method in RCooper scenarios.
We will continue to work with CAIC to update the calibration parameters.

The same discussion can also be found [here](https://github.com/AIR-THU/DAIR-RCooper/issues/15)
