### ISSUE TITLE
关于行人、自行车等类别的baselines

### ISSUE THREAD

**Issue by xf-zh** [AIR-THU/DAIR-RCooper#33]
您好，请问在rcooper数据集中是否有计划公开自行车、行人、货车等类别在跟踪和检测任务中的baseline？

**Comment by ryhnhao** [comment]
您好，感谢您的关注。我们会持续在RCooper上开展相关研究。
但因为项目的推进，尚且没有具体的时间表，我们鼓励社区进行探索！
