### ISSUE TITLE
Can the dataset support the apis of camera?

### ISSUE THREAD

**Issue by WangzcBruce** [AIR-THU/DAIR-RCooper#35]

**Comment by ryhnhao** [comment]
Thank you for your patience, and sorry for the delayed response. 
We have provided a LiDAR-based benchmark within our codebase. However, unfortunately, we have not yet developed a fully available API for camera.
You may consider transferring RCooper to other format ([here](https://github.com/AIR-THU/DAIR-RCooper/tree/main/codes/dataset_converter)) for their camera-apis. 

We also acknowledge that there is inaccurate calibration in this version of data as the discussion in [issue 32](https://github.com/AIR-THU/DAIR-RCooper/issues/32) and [issue 15](https://github.com/AIR-THU/DAIR-RCooper/issues/15).
