### ISSUE TITLE
Camera的内参外参

### ISSUE THREAD

**Issue by sidiangongyuan** [AIR-THU/DAIR-RCooper#36]
请问将数据集转换成opv2v格式之后，如何获取相机对应的内参和外参？我在yaml文件里没有找到。

**Comment by sidiangongyuan** [comment]
找到了，已经成功读取camera参数了。

**Comment by hexunjie** [comment]
请问从哪里读取的呀

**Comment by sidiangongyuan** [comment]
你可以参考项目中转换到nus数据集格式的代码，里面有每个相机的 写死的内参和外参数据

hexunjie ***@***.***> 于2024年12月9日周一 15:43写道：
