### ISSUE TITLE
关于label的问题

### ISSUE THREAD

**Issue by sidiangongyuan** [AIR-THU/DAIR-RCooper#37]
转换成opv2v的格式之后，发现label里面的vehicles 个数很少，一般只有3，4个？ 这正常吗？

**Comment by ryhnhao** [comment]
您好，感谢关注。
事实上，在个别场景中vehicle确实比较少，可能该时段路上vehicle本来就很少，在corridor场景中这种现象可能更容易出现。
至于label有没有减少，您可以对比一下格式变换前后的label数量

**Comment by sidiangongyuan** [comment]
> 您好，感谢关注。 事实上，在个别场景中vehicle确实比较少，可能该时段路上vehicle本来就很少，在corridor场景中这种现象可能更容易出现。 至于label有没有减少，您可以对比一下格式变换前后的label数量

OK, 我check 一下，  还有个问题，cav_range的z 设置成  -11 ~ 0 合理吗？ 在OPV2V的dataloader处理过程中，我发现很多label会被筛除， 经常出现没有有效label的情况，  改成 -20 ~ 10  则会正常。 不知道这是否存在问题？

**Comment by ryhnhao** [comment]
> > 您好，感谢关注。 事实上，在个别场景中vehicle确实比较少，可能该时段路上vehicle本来就很少，在corridor场景中这种现象可能更容易出现。 至于label有没有减少，您可以对比一下格式变换前后的label数量
> 
> OK, 我check 一下， 还有个问题，cav_range的z 设置成 -11 ~ 0 合理吗？ 在OPV2V的dataloader处理过程中，我发现很多label会被筛除， 经常出现没有有效label的情况， 改成 -20 ~ 10 则会正常。 不知道这是否存在问题？

抱歉回复较慢
我们是根据事实上lidar设备的放置高度”设置了这个值来滤除可能的错误标注，所以理论上应该是正常的
