### ISSUE TITLE
标注准确性

### ISSUE THREAD

**Issue by DashingPanda** [AIR-THU/DAIR-RCooper#38]
<img width="204" alt="image" src="https://github.com/user-attachments/assets/73768c63-5691-4fd0-b79b-be3775ba6704">

你好，从你们的论文图片中看到的3D标注框与目标明显不贴合，想知道为什么会有这种情况呢，是激光雷达和相机的数据采集时间不同步吗，还是其它什么原因

**Comment by ryhnhao** [comment]
您好，感谢关注，很抱歉造成这种困扰

根据我们目前的掌握，这个现象更有可能是路口场景117-120的标定并不准确，造成这种可视化结果的偏差
您可以在这两个issue中看到关于这个问题的讨论：[issue32](https://github.com/AIR-THU/DAIR-RCooper/issues/32) and [issue32](https://github.com/AIR-THU/DAIR-RCooper/issues/15).
我们仍在与CAIC协作来继续更新相机内外参
