### ISSUE TITLE
关于数据集的内容

### ISSUE THREAD

**Issue by sidiangongyuan** [AIR-THU/DAIR-RCooper#39]
在intersection部分只有路端的数据吗？ 不是类似dair-v2x那样的？
camera数据只有一个

**Comment by ryhnhao** [comment]
是的，只有路端数据。
RCooper 在底层概念上更类似于 Infrastructure to Infrastructure (I2I) 的数据集，不涉及 Vehicle 视角的协同感知 (V2I or V2X)
涉及 Vehicle视角的协同感知可以参考 各个V2X数据集

**Comment by sidiangongyuan** [comment]
> 是的，只有路端数据。 RCooper 在底层概念上更类似于 Infrastructure to Infrastructure (I2I) 的数据集，不涉及 Vehicle 视角的协同感知 (V2I or V2X) 涉及 Vehicle视角的协同感知可以参考 各个V2X数据集

感谢
