### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by githigher** [AIR-THU/DAIR-RCooper#4]
When I was preparing for training, I ran the following code:
`
bash scripts/det_train_corridor_fcooper.sh
`
But the following error occurred：

Traceback (most recent call last):
  File "opencood_plugin/opencood/tools/train.py", line 15, in <module>
    import opencood.hypes_yaml.yaml_utils as yaml_utils
ModuleNotFoundError: No module named 'opencood'

I checked that there is a file named __ init__. py in the opencool folder, but I don't know why an error occurred.

**Comment by githigher** [comment]
I have observed that there is an OpenCOOD-main/setup.py file in the official code repository of opencood. I suspect that it is due to the missing setup.py file in the code repository you provided, which resulted in the ModuleNotFoundError.

**Comment by githigher** [comment]
After my experiment, you can save the following code as a setup.py file:
```
# -*- coding: utf-8 -*-
# Author: Runsheng Xu <rxx3386@ucla.edu>
# License: TDG-Attribution-NonCommercial-NoDistrib


from os.path import dirname, realpath
from setuptools import setup, find_packages, Distribution
from opencood.version import __version__


def _read_requirements_file():
    """Return the elements in requirements.txt."""
    req_file_path = '%s/requirements.txt' % dirname(realpath(__file__))
    with open(req_file_path) as f:
        return [line.strip() for line in f]


setup(
    name='OpenCOOD',
    version=__version__,
    packages=find_packages(),
    url='https://github.com/ucla-mobility/OpenCDA.git',
    license='MIT',
    author='Runsheng Xu, Hao Xiang',
    author_email='rxx3386@ucla.edu',
    description='An opensource pytorch framework for autonomous driving '
                'cooperative detection',
    # long_description=open("README.md").read(),
    # install_requires=_read_requirements_file(),
)
```
Then place it in a directory at the same level as opencool, and finally run the following command:
```
python setup.py develop
```
This is equivalent to downloading the opencood library directly, and you can use "conda list" to check it. I am confident that this can solve the ModuleNotFoundError, and I also hope that the author can resolve this bug.

**Comment by ryhnhao** [comment]
Thanks for your valuable feedback!
This is an issue caused by mistake when reorganizing the codebase.

We will fix this bug.
Thanks a lot!

**Comment by ryhnhao** [comment]
Hi @githigher Thanks for your valuable suggestion!
We have updated related readmes.
Thanks a lot!
