### ISSUE TITLE
problem accessing dataset

### ISSUE THREAD

**Issue by angelmancar** [AIR-THU/DAIR-RCooper#40]
Thank you very much for your work!

I am trying to ask for access for the RCooper dataset via the website, but when it asks me for my contact information, it gives the error "Please fill in the correct mobile phone number" in the phone number section. Any idea why this might be? Would really love to use the dataset for my research!

**Comment by ryhnhao** [comment]
Hi @angelmancar , thanks for your attention.
You may leave your detail in [this issue](https://github.com/AIR-THU/DAIR-RCooper/issues/22), and we will help you with dataset access.
