### ISSUE TITLE
 Inquiry on IOUthres Utilization in AB3DMOT Benchmark

### ISSUE THREAD

**Issue by liyn69** [AIR-THU/DAIR-RCooper#41]
Thanks for your excellent work!

I have been reviewing your work on tracking tasks where you have employed the AB3DMOT benchmark for evaluation purposes. I am interested in the specific values of IOU threshold (IOUthres) that your team has adopted, as referenced in Tables 5 and 6.

Thank you for your attention to this matter. Looking forward to your response!

**Comment by ryhnhao** [comment]
Hi, @liyn69. Sorry for the late response.
The parameter setting can be find in [here](https://github.com/AIR-THU/DAIR-RCooper/blob/514a1d7547c36cdede68cd6a22378bb50129e938/codes/ab3dmot_plugin/AB3DMOT_plugin/AB3DMOT_libs/model.py#L504), hope it helps!

**Comment by liyn69** [comment]
Thanks for your reply，I would also like to know if the tracking results in the article are obtained according to the parameter settings in eval_tracking.py.
https://github.com/AIR-THU/DAIR-RCooper/blob/514a1d7547c36cdede68cd6a22378bb50129e938/codes/ab3dmot_plugin/eval_tracking.py#L59

**Comment by ryhnhao** [comment]
> Thanks for your reply，I would also like to know if the tracking results in the article are obtained according to the parameter settings in eval_tracking.py.
> 
> https://github.com/AIR-THU/DAIR-RCooper/blob/514a1d7547c36cdede68cd6a22378bb50129e938/codes/ab3dmot_plugin/eval_tracking.py#L59

Hi, @liyn69, the parameters at mentioned line is not relevant. We are sorry for not cleaning the unnecessary codes.

For the real setting procedure, you can follow the following (You may see the same procedure when debugging):
https://github.com/AIR-THU/DAIR-RCooper/blob/514a1d7547c36cdede68cd6a22378bb50129e938/codes/ab3dmot_plugin/AB3DMOT_plugin/main_tracking.py#L61

https://github.com/AIR-THU/DAIR-RCooper/blob/514a1d7547c36cdede68cd6a22378bb50129e938/codes/ab3dmot_plugin/AB3DMOT_plugin/AB3DMOT_libs/utils.py#L93

https://github.com/AIR-THU/DAIR-RCooper/blob/514a1d7547c36cdede68cd6a22378bb50129e938/codes/ab3dmot_plugin/AB3DMOT_plugin/AB3DMOT_libs/model.py#L504

**Comment by liyn69** [comment]
Sorry to bother you, I didn’t express myself clearly. I’d like to know what 3D IOU threshold(Matching criteria) you’ve set, like in the AB3DMOT paper, whether it's 0.25, 0.5, or 0.7. Is it the 0.25 set in eval_tracking.py? Also, I’d like to know which class you’ve chosen.

Thanks.

**Comment by ryhnhao** [comment]
> Sorry to bother you, I didn’t express myself clearly. I’d like to know what 3D IOU threshold(Matching criteria) you’ve set, like in the AB3DMOT paper, whether it's 0.25, 0.5, or 0.7. Is it the 0.25 set in eval_tracking.py? Also, I’d like to know which class you’ve chosen.
> 
> Thanks.

Hi, @liyn69. Sorry for the late response and my previous misdirection.
3D IOU threshold is 0.25 for evaluation as you indicated. And as mentioned in our paper, we merge classes into one class "CAR".
