### ISSUE TITLE
camera intrinsic

### ISSUE THREAD

**Issue by hexunjie** [AIR-THU/DAIR-RCooper#46]
What's  the corresponding yaml for each scenario's cars? Does the 117-118-120-119 represents the car 0-1-2-3?

**Comment by ryhnhao** [comment]
Hi, @hexunjie 
RCooper is designed for roadside cooperative perception **(Not for V2I or V2X)**, so there is not vehicles' intrinsic yaml.
117-118-120-119 represents views from four roadside units. Part of Fig.4 in original paper as shown below may help.
![image](https://github.com/user-attachments/assets/140375e9-fbe7-4880-ac93-1b1c85f81244)
