### ISSUE TITLE
Data Heterogeneity

### ISSUE THREAD

**Issue by githigher** [AIR-THU/DAIR-RCooper#8]
In intersection scenes, you configure two types of LiDARs, Multiline LiDARs Group and MEMS LiDARs. I would like to know if it is possible to get the type of LIDAR features in the code.😊

**Comment by leofansq** [comment]
Towards the unified cooperative perception for practical application, we didn't distinguish the types in the code. 
However, you can get the type according to the infrastructure's IDs.

Multiline LiDAR: 117, 120, 136, 139
MEMS LiDAR: 118, 119, 137, 138

**Comment by githigher** [comment]
Thank you very much for your reply!
Can you be more specific as to where the code to get the infrastructure ID is located? I'd like to try two different encoders for Multiline LiDARs Group and MEMS LiDARs.

**Comment by leofansq** [comment]
* For the raw RCooper dataset, you can directly distinguish the ID in data folder.
* For the converted OPV2V-format or V2V4Real-format dataset, you can distinguish the infrastructures according to the following mapping relationship
    * '116-115' scenario: 116 ---> 0, 115 ---> 1
    * '106-105' scenario: 106 ---> 0, 105 ---> 1
    * '117-118-120-119' scenario: 117 ---> 0, 118 ---> 1, 120 ---> 2, 119 ---> 3
    * '136-137-138-139' scenario: 136 ---> 0, 137 ---> 1, 138 ---> 2, 139 ---> 3
